"""Constants for the Intex WA510 custom integration."""

DOMAIN = "intex_wa510"

CONF_ACCESS_ID = "access_id"
CONF_ACCESS_SECRET = "access_secret"
CONF_DEVICE_ID = "device_id"
CONF_ENDPOINT = "endpoint"

DEFAULT_ENDPOINT = "https://openapi.tuyaeu.com"
DEFAULT_SCAN_INTERVAL = 300

STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}_maintenance"

DEFAULT_CLEANING_DAYS = 30
DEFAULT_PH_CALIBRATION_DAYS = 120
DEFAULT_ORP_CALIBRATION_DAYS = 120

DEVICE_NAME = "Pool Water Analyzer"
DEVICE_MANUFACTURER = "Intex / AGP / Tuya"
DEVICE_MODEL = "WA510 / AGP SMART SENSOR T3U"
DEVICE_SW_VERSION = "0.6.3"

FAST_REFRESH_SECONDS = 30
FAST_REFRESH_INTERVAL = 5
